server:
  port: 8900
spring:
  application:
    name: APIGATEWAY-SERVICE
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)
  cloud:
    gateway:
      routes:
      - id: BookQueryModule
        uri: lb://BOOKQUERY-SERVICE
        predicates:
        - Path=/bookquery/**
      - id: BookCommandModule
        uri: lb://BOOKCOMMAND-SERVICE
        predicates:
        - Path=/book/**
      - id: BorrowingModule
        uri: lb://BORROWING-SERVICE
        predicates:
        - Path=/borrowing/**
      - id: CustomerModule
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/customer/**
      - id: ReviewModule
        uri: lb://REVIEW-SERVICE
        predicates:
        - Path=/review/**
#      filter:
#        rewrite-path:
#          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
