server:
  port: 8080
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: EUREKA-SERVICE
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)
