
spring:
  application:
    name: LIBRARY-SERVICE
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)
  cloud:
    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 8906